# Generated by Django 3.1.7 on 2021-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytip',
            name='published',
        ),
        migrations.AlterField(
            model_name='dailytip',
            name='posted_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
