# Generated by Django 3.1.7 on 2021-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_id', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateField()),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
