# Generated by Django 3.1.7 on 2021-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20210321_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
