# Generated by Django 3.1.7 on 2021-03-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20210321_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytip',
            name='likes',
            field=models.CharField(blank=True, default='', max_length=999999),
        ),
        migrations.AddField(
            model_name='dailytip',
            name='retweets',
            field=models.CharField(blank=True, default='', max_length=999999),
        ),
    ]
