# Generated by Django 3.1.7 on 2021-03-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20210321_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytip',
            options={'ordering': ['-retweets']},
        ),
        migrations.AlterField(
            model_name='dailytip',
            name='retweets',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
