# Generated by Django 3.1.7 on 2021-03-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_auto_20210323_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('expanded_url', models.URLField()),
                ('display_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dailytip',
            name='display_url',
        ),
        migrations.RemoveField(
            model_name='dailytip',
            name='expanded_url',
        ),
        migrations.RemoveField(
            model_name='dailytip',
            name='url',
        ),
        migrations.AddField(
            model_name='dailytip',
            name='urls',
            field=models.ManyToManyField(to='tips.TweetLinks'),
        ),
    ]
