# Generated by Django 3.1.7 on 2021-03-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_auto_20210323_0332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dailytip',
            managers=[
            ],
        ),
    ]
