# Generated by Django 3.1.7 on 2021-03-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20210323_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDailyTip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('python_tip', models.CharField(max_length=140)),
                ('your_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
