# Generated by Django 3.1.7 on 2021-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_postdailytip_your_twitter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
